### ISSUE TITLE
No entry paths found(Nodejs)

### ISSUE THREAD

**Issue by AliElKhatteb** [dependency-check-team/dependency-check#138]
i tried to run this command
dependency-check ./package.json --verbose
and it gives me this error
No entry paths found

**Comment by kevinkdev** [comment]
Hey any updates on this? I am also trying to scan my package.json and got  "No entry paths found"

**Comment by tomtapia** [comment]
Hi everyone,
I've the same error when I trying to run the command in my project.
`dependency-check ./package.json --verbose`
However, I received this message all the time "No entry paths found".
![image](https://user-images.githubusercontent.com/419426/129267430-0fde5c88-9a87-4917-90c9-22ed35b17f3f.png)
Please, help us to find a solution or if you need more information about it, let me know to help you.
Cheers!!!

**Comment by voxpelli** [comment]
It means that it neither found the file defined in the `main` key of `./package.json` (defaults to `./index.js` if missing) nor any files in the `bin` key (string or array of strings)

What you then can do is to explicitly specify the paths to your files:

```bash
dependency-check ./src/index.js ./src/foo.js
```

Or use globbing (unless you wrap the glob pattern with `'` it will get resolved by your shell rather than by `dependency-check`, which may also works, but depends on your shell supporting the full glob pattern and especially cross-platform that can be a challenge):

```bash
dependency-check './src/**/*.js'
```

**Comment by voxpelli** [comment]
Closing, happy to reopen of any of you still have an issue. Sorry for slow response 😞
